INSERT INTO PRODUCT (PRODUCTID, CATEGORY, SUBCATEGORY, PRODUCTNAME)
VALUES (1,'SPORTS','FOOTBALL','BOTAS');

SELECT *
FROM PRODUCT;

INSERT INTO PRODUCT (PRODUCTID, CATEGORY, SUBCATEGORY, PRODUCTNAME)
VALUES (1,'SPORTS','FOOTBALL','BOTAS'),(2,'SPORTS','GOLF','PALOS');

ALTER TABLE PRODUCT
ADD COUNTRY VARCHAR(50);

SELECT *
FROM PRODUCT;