SELECT *
FROM CUSTOMER
WHERE C_MKTSEGMENT = 'HOUSEHOLD' OR C_NATIONKEY = 5
LIMIT 25;

SELECT *
FROM CUSTOMER
WHERE C_MKTSEGMENT IN ('HOUSEHOLD', 'BUILDING')
LIMIT 20;

SELECT *
FROM CUSTOMER
WHERE C_CUSTKEY BETWEEN 60001 AND 60030;

SELECT *
FROM CUSTOMER
WHERE C_MKTSEGMENT LIKE 'B%'
LIMIT 20;

SELECT C_CUSTKEY AS CLIENTE_KEY, C_NAME AS NOMBRE
FROM CUSTOMER WHERE C_MKTSEGMENT = 'BUILDING'
ORDER BY C_CUSTKEY ASC
LIMIT 20;

SELECT COUNT (C_NAME) AS TOTAL_NOMBRES
FROM CUSTOMER;

SELECT *
FROM CUSTOMER;

SELECT C_NATIONKEY AS COUNTRY, COUNT(C_NAME) AS TOTAL_NOMBRES
FROM CUSTOMER
GROUP BY C_NATIONKEY;

SELECT C_NATIONKEY AS COUNTRY, COUNT(C_NAME) AS TOTAL_NOMBRES
FROM CUSTOMER
GROUP BY C_NATIONKEY
HAVING TOTAL_NOMBRES >= 6000;
